config/routes.rb
Rails.application.routes.draw do
  # clearance
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  # thredded
  mount Thredded::Engine => '/forum'

  # bookmarks
  resources :bookmarks

  # media
  resources :media do
    resources :comments
  end

  # torrent
  resources :torrents

  # user
  resources :users



  # home page
  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :torrents
  has_many :bookmarks

  #validates_presence_of :username
  #validates_uniqueness_of :username

  #def self.authenticate(email, password)
   #user = find(:first, :conditions => ['username = ? OR email = ?', email.to_s.downcase, #email.to_s.downcase])
   #user && user.authenticated?(password) ? user : nil
 #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show

  end

  def user_params
    params.require(:user).permit(:username)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/views/users/index.html.erb
<% breadcrumb :users %>
<h2>Users</<h2>

<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% breadcrumb :user, @user %>

<h2><%= @user.username %></h2>

<p>
  Uploaded:
  <%= @user.torrents.count %>
  <%= link_to 'View', media_path(q: {torrents_user_id_cont: 1}) %>
</p>