config/routes.rb
Rails.application.routes.draw do
  # clearance
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  # thredded
  mount Thredded::Engine => '/forum'

  # bookmarks
  resources :bookmarks

  # media
  resources :media do
    resources :comments
  end

  # torrent
  resources :torrents

  # user
  resources :users



  # home page
  root 'welcome#index'
end

app/models/torrent.rb
class Torrent < ApplicationRecord
  belongs_to :medium
  belongs_to :user
end

app/controllers/torrents_controller.rb
class TorrentsController < ApplicationController

  def index
    @q = Torrent.ransack(params[:q])
    @torrents = @q.result.page(params[:page]).per(25)
  end

  def show
    @torrent = Torrent.find(params[:id])
  end

  def new
    @torrent = Torrent.new

    if params[:medium_id]
      @medium = Medium.find(params[:medium_id])
    else
      @medium = ''
    end
  end

  def edit
    @torrent = Torrent.find(params[:id])
  end

  def create
    search = Tmdb::Movie.find(params['torrent']['title'])

    medium = Medium.where(
      title: search[0].title,
      body: search[0].overview,
      poster: 'https://image.tmdb.org/t/p/w300_and_h450_bestv2' + search[0].poster_path,
      api_id: search[0].id
    ).first_or_create

    if medium.id
      @torrent = Torrent.create({
        :title => 'test titre',
        :body => params['torrent']['body'],
        :medium_id => medium.id,
        :user_id => current_user.id
      })

      redirect_to medium_path(medium)
    end
  end

  def update
		@torrent = Torrent.find(params[:id])

		if @torrent.update(torrent_params)
			redirect_to @torrent
		else
			render 'edit'
		end
	end

  def destroy
		@torrent = Torrent.find(params[:id])
		@torrent.destroy

		redirect_to torrents_path
	end

  private
    def torrent_params
      params.require(:torrent).permit(:title, :body)
    end
end

app/helpers/torrents_helper.rb
module TorrentsHelper
end

app/views/torrents/_form.html.erb
<%= form_for @torrent do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class:'form-control' %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, class:'form-control' %>
  </p>

  <p>
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
  </p>

  <% if local_assigns[:delete] %>
    <p>
      <%= link_to 'Delete', @torrent,
                   method: :delete,
                   data: { confirm: 'Are you sure?' },
                   :class => 'btn btn-danger' %>
    </p>
  <% end %>
<% end %>

app/views/torrents/_torrent.html.erb
<p><%= torrent.body %></p>

app/views/torrents/edit.html.erb
<h1>Edit torrent</h1>

<%= render 'form', delete: true %>

<%= link_to 'Back', torrents_path %>

app/views/torrents/index.html.erb
<h1>Torrents</h1>
<table class="table">
  <tr>
    <th><%= sort_link(@q, :title) %></th>
    <th><%= sort_link(@q, :body) %></th>
  </tr>

  <% @torrents.each do |torrent| %>
    <tr>
      <td><%= torrent.title %></td>
      <td><%= torrent.body %></td>
      <td><%= link_to 'Show', torrent_path(torrent) %></td>
    </tr>
  <% end %>
</table>
<%= paginate @torrents %>

app/views/torrents/new.html.erb
<h1>Upload torrent</h1>

<!--<%= render 'media/form' %>

<% if @medium != '' %>
  <%= @medium.title %>
<% end %>-->

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/torrents/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @torrent.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @torrent.body %>
</p>

<%= @torrent.medium_id %>


<%= link_to 'Edit', edit_torrent_path(@torrent) %> |
<%= link_to 'Back', torrents_path %>